Почему класс AccessDeniedException в нашем случае
лучше наследовать от Exception, а не от RuntimeException?

class AccessDeniedException extends Exception {

}

=======================================================
Возможно потому, что результаты проверок, связанных с безопасностью
(доступ к данным и т. п.), не должны игнорироваться. Наследование от
Exception вынуждает нас перехватить и обработать данное исключение.